image: docker:23.0.4

services:
  - docker:23.0.4-dind

stages:
  - build

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build-bukkit-plugin-deploy-helper:
  stage: build
  variables:
    IMAGE: "${CI_REGISTRY_IMAGE}/bukkit-plugin-deploy-helper"
  rules:
    - changes:
        - .gitlab-ci.yml
        - bukkit-plugins/deploy-helper/**/*
  script:
    - if [[ $CI_PIPELINE_SOURCE != "schedule" ]]; then docker pull $IMAGE:latest || true; fi
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $IMAGE:latest
      --tag $IMAGE:latest
      --push
      bukkit-plugins/deploy-helper