image: maven:3-openjdk-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script: mvn compile

test:
  stage: test
  script: mvn test
  dependencies:
    - build

release:
  stage: package
  script: mvn package
  dependencies:
    - test
  artifacts:
    paths:
      - target/*.jar
  only:
    - tags

snapshot-release:
  stage: package
  script: mvn package
  dependencies:
    - test
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

deploy-release:
  stage: deploy
  image: registry.gitlab.com/programie/common/bukkit-plugin-deploy-helper
  dependencies:
    - release
  script: /deploy.py
  only:
    - tags