image: docker:23.0.4

services:
  - docker:23.0.4-dind

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - if [[ $DOCKER_HUB_REPO ]]; then echo -n $DOCKER_HUB_TOKEN | docker login -u programie --password-stdin; fi

Build-Main:
  stage: build
  only:
    - main
    - master
  script:
    - if [[ -z $BUILD_SKIP_DOCKER_PULL ]]; then docker pull $CI_REGISTRY_IMAGE:latest || true; fi
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      --push
      .
    - >
      if [[ $DOCKER_HUB_REPO ]]; then
        docker tag $CI_REGISTRY_IMAGE:latest programie/$DOCKER_HUB_REPO:latest
        docker push programie/$DOCKER_HUB_REPO:latest
      fi

Build-Release:
  stage: build
  only:
    - tags
  script:
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      --push
      .
    - >
      if [[ $DOCKER_HUB_REPO ]]; then
        docker tag $CI_REGISTRY_IMAGE:latest programie/$DOCKER_HUB_REPO:$CI_COMMIT_REF_NAME
        docker push programie/$DOCKER_HUB_REPO:$CI_COMMIT_REF_NAME
      fi